name: dagger
on:
  push:
    branches: [main]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Call Dagger Function to publish to ghcr
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          verb: call
          args: publish-ghcr --username=$DOCKER_USERNAME --password=env://DOCKER_PASSWORD --src=.
        env:
          DOCKER_REGISTRY: ghcr.io
          DOCKER_IMAGE_NAME: ${{ github.repository }}
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
